version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.1.17
    - 6.2.1
    - 6.2.2
    - 6.2.4
    - 6.2.5
    - 6.2.9
  - dependency-name: "@types/node"
    versions:
    - 14.14.26
    - 14.14.36
    - 15.0.0
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.1
    - 6.2.2
    - 6.2.4
    - 6.2.5
    - 6.2.8
    - 6.2.9
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.13
    - 13.0.6
    - 13.1.2
    - 13.1.3
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.1
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.8
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.1.16
    - 6.1.19
    - 6.1.21
    - 6.2.1
    - 6.2.2
    - 6.2.4
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: eslint-config-prettier
    versions:
    - 8.2.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
    - 7.13.15
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.4
  - dependency-name: next-pwa
    versions:
    - 5.2.1
    - 5.2.3
    - 5.2.5
  - dependency-name: next
    versions:
    - 10.1.2
  - dependency-name: react-is
    versions:
    - 17.0.2
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
  - dependency-name: "@apollo/client"
    versions:
    - 3.3.8
