backend:
  name: github
  repo: uselessdev/iamwallace
  branch: main

publish_mode: editorial_workflow
media_folder: public/images
public_folder: images

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - label: 'Categorias'
        name: 'categories'
        widget: 'select'
        multiple: true
        options: [
          'React',
          'GraphQL',
          'Game Development',
          'Frontend',
          'Backend',
          'Não faço ideia'
        ]
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Cover', name: 'cover', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
