backend:
  name: git-gateway
  branch: main
  repo: uselessdev/iamwallace
  site_domain: https://iamwallace.netlify.app/

publish_mode: editorial_workflow
media_folder: public/images
public_folder: images

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - { label: 'Data', name: 'published_at', widget: 'datetime' }
      - { label: 'Descrição', name: 'excerpt', widget: 'string' }
      - { label: 'Capa', name: 'thumbnail', widget: 'image' }
      - label: 'Categoria'
        name: 'category'
        widget: 'select'
        options: ['React', 'GraphQL']
      - { label: 'Artigo', name: 'content', widget: 'markdown' }
