backend:
  name: github
  repo: uselessdev/iamwallace
  branch: main

publish_mode: editorial_workflow
media_folder: public/images
public_folder: images

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - label: 'Categorias'
        name: 'categories'
        widget: 'select'
        options:
          - { label: 'React', value: 'react' }
          - { label: 'GraphQL', value: 'graphql' }
          - { label: 'Game Development', value: 'game-development' }
          - { label: 'Frontend', value: 'frontend' }
          - { label: 'Backend', value: 'backend' }
          - { label: 'Não faço ideia', value: 'nao-faco-ideia' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Cover', name: 'cover', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
