backend:
  name: github
  repo: uselessdev/iamwallace
  branch: main

publish_mode: editorial_workflow
media_folder: public/images
public_folder: images

collections:
  - name: 'categories'
    label: 'Categorias'
    folder: 'content/categories'
    create: true
    fields:
      - { label: 'Nome', name: 'name', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Cor de fundo', name: 'color', widget: 'string' }

  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - { label: 'Data', name: 'date', widget: 'datetime' }
      - { label: 'Descrição', name: 'description', widget: 'string' }
      - { label: 'Capa', name: 'cover', widget: 'image' }
      - label: 'Categoria'
        name: 'category'
        widget: 'select'
        options: ['React', 'GraphQL', 'Game Development']
      - { label: 'Artigo', name: 'body', widget: 'markdown' }
